### ISSUE TITLE
Something getting wrong -> Something went wrong

### ISSUE THREAD

**Issue by necro-nemesis** [graft-project/GraftMobile#12]
https://github.com/graft-project/GraftMobile/blob/6ccfc8ea168203a7e2573f89278e5564ba83cc89/GraftMobileClient/resources/PaymentScreen.qml#L135

**Comment by EDDragonWolf** [comment]
Thanks. We'll fix it in the next release.

**Comment by necro-nemesis** [comment]
I see it was fixed 15hrs ago. Closing.
