### ISSUE TITLE
RTA Pay: Wallet can't pay until previous tx get mined

### ISSUE THREAD

**Issue by mbg033** [graft-project/GraftMobile#62]
tx rejected with double spend

**Comment by Swericor** [comment]
I haven't experienced this, however if the payment wallet does not have enough outputs only a single RTA transaction can be made, after which all funds will be locked. I have successfully made three consecutive RTA payments by first ensuring that the payment wallet has enough outputs. This is nevertheless a bug that needs to be addressed.

**Comment by mbg033** [comment]
looks like this is how `wallet2::refresh` works currently. Tested with two `graft-wallet-cli` instances running on the same wallet (two copies of the same wallet). in case we spend money with wallet1 - wallet2 only sees it when tx get mined into block but not when it is in mempool. To be checked if this is the bug or implemented by intent.

**Comment by mbg033** [comment]
fixed in GraftNoded https://github.com/graft-project/GraftNetwork/commit/e2d46c0cf72d1d6512c049d92da7d18e58cddee1
